#!/bin/sh
# he-ports: Fast shell-based port scanner for Helium OS

TARGET="${1:-localhost}"
START_PORT="${2:-1}"
END_PORT="${3:-1024}"

COMMON_PORTS="21 22 23 25 53 80 110 143 443 3306 8080"

printf "Helium Port Scanner\n"
printf "Scanning target: \033[1;36m%s\033[0m\n" "$TARGET"
printf "%-10s %s\n" "PORT" "STATUS"
printf "--------------------\n"

if [ -n "$2" ] && [ -n "$3" ]; then
    # Scan range
    PORT=$START_PORT
    while [ "$PORT" -le "$END_PORT" ]; do
        nc -z -w 1 "$TARGET" "$PORT" 2>/dev/null
        if [ $? -eq 0 ]; then
            printf "%-10s \033[1;32mOPEN\033[0m\n" "$PORT"
        fi
        PORT=$((PORT + 1))
    done
else
    # Scan common ports
    for PORT in $COMMON_PORTS; do
        nc -z -w 1 "$TARGET" "$PORT" 2>/dev/null
        if [ $? -eq 0 ]; then
            printf "%-10s \033[1;32mOPEN\033[0m\n" "$PORT"
        else
            printf "%-10s \033[1;31mCLOSED\033[0m\n" "$PORT"
        fi
    done
fi

printf "Scan complete.\n"
